### ISSUE TITLE
Validate nested arrays throws exception

### ISSUE THREAD

**Issue by ZehuaZhang** [Redocly/openapi-sampler#119]
Schema
```
{
  type: "array",
  "x-nullable": false,
  items: {
    type: "array",
    items: {
      type: "string",
      minLength: 1,
    },
  },
  description: "nested arrays"
}
```
Validation 
```
validator.validateModel(
      [
        ['1'],['2']
      ],
     schema,
```
Error
```
TypeError: Cannot set property 'arrayPos' of undefined
    at /Users/node_modules/swagger-object-validator/lib/validators/ArrayValidator.js:40:48
    at Array.forEach (<anonymous>)
    at validateArray (/Users/node_modules/swagger-object-validator/lib/validators/ArrayValidator.js:38:10)
    at /Users//node_modules/swagger-object-validator/lib/validators/ModelValidator.js:58:29
From previous event:
    at Object.validateModel (/Users/node_modules/swagger-object-validator/lib/validators/ModelValidator.js:26:10)
    at /Users/node_modules/swagger-object-validator/lib/handler.js:46:67
From previous event:
    at /Users/node_modules/swagger-object-validator/lib/handler.js:46:18
```

**Comment by RomanHotsiy** [comment]
Hey ✋ ,

Please, report this issue in swagger-object-validator, this is not openapi-sampler issue.

The sampler output is correct: https://www.jsonschemavalidator.net/s/6wyVrh7h
